### ISSUE TITLE
Getting all global Option Sets?

### ISSUE THREAD

**Issue by mgibbs189** [bigcommerce/bigcommerce-for-wordpress#116]
Hi, this is more of a question / feature request.

I'm the author of FacetWP, and we've started looking into BigCommerce integration. Overall the data is structured well and is straight-forward to access. 👍 

When someone creates a facet, they choose which "Data Source" (e.g. Price, Weight, Brand, Size, etc.) to pull data from.

We're having a hard time figuring out how to efficiently grab the list of available **Option Sets** (and thus every option). Is there a way to get this data without having to loop through every single product? Or perhaps this data could be synced to WP as a `bigcommerce_option_sets` wp_option?

Also, some products use `bigcommerce_options_data` (variable products?) postmeta whereas other products use `bigcommerce_modifier_data`. Any chance you could explain this a bit further?

**Comment by karen-white** [comment]
Hey @mgibbs189 , the list of all option sets are available through the legacy v2 products API:

https://developer.bigcommerce.com/legacy/v2-catalog-products/v2-option-sets#v2-option-set_list-option-set

For context, in our v2 product model, product options were contained in option sets, which were attached to products. In the v3 product model, options are attached directly to products and the concept of option sets goes away. More on that [here](https://developer.bigcommerce.com/legacy/v2-products/v2-v3). 

Although the product edit page in the control panel still reflects the v2 model, we're transitioning to the v3 product model long term. In the meantime, the v2 product API will continue to be a method you can use to get v2 option set data. Our plugin consumes the v3 API, which is why we don't currently sync option sets to WP.

For the difference between `bigcommerce_options_data` and `bigcommerce_modifier_data`, both are choices that are attached to products, but the v3 products API makes a distinction between product choices that are used to built out SKUs (variant options) and choices that don't build out SKUs (modifier options).

An example would be a t-shirt that has size and color options, along with a text field option to add some custom embroidery for $5 extra. Size and color are `variant options` that build out a SKU: a physical item as it sits in the warehouse. For example, a small/red shirt. The text field to add embroidery is a `modifier option`: it doesn't affect the SKU as it sits in the warehouse, but it does represent a selectable choice and it does add a price adjustment when selected.

Hope this helps provide some clarity and a way forward!

**Comment by mgibbs189** [comment]
Thanks for the detailed response @karen-white 👍 

Is the v2 API deprecated? Since this is for a new project, I'd prefer an approach that won't require a rewrite further down the road.

I'm leaning towards looping through all products to grab (and cache) their options, versus relying on the v2 API. Unless the plan is for v2 to remain indefinitely?

**Comment by topher1kenobe** [comment]
I think looping isn't really an option, for performance reasons.  We should probably make this a feature request for v3.
