### ISSUE TITLE
Cart is not displaying item count when product is added to the cart

### ISSUE THREAD

**Issue by tcobfitzroy** [bigcommerce/bigcommerce-for-wordpress#181]
### Expected behaviour
Item count should display when product is added to cart.

### Actual behavior
No item count displays

**Comment by becomevocal** [comment]
@tcobfitzroy this might have been because previous versions of the plugin required the embedded checkout option and SSL to be enabled to show the item count. The latest version performs a cart request after the page load so it's compatible with both the full checkout that redirects to BC and the embedded checkout. So try the latest version (3.11.0) to see if this is resolved!

**Comment by topher1kenobe** [comment]
Closing, due to fix in later version.
