### ISSUE TITLE
Visible on storefront BC setting being used for channels

### ISSUE THREAD

**Issue by topher1kenobe** [bigcommerce/bigcommerce-for-wordpress#239]
### The "Visible on storefront" BC setting should not be used for channels, it should be used ONLY for the main BC storefront.  To manipulate visibility of products in channels the add/remove from channels feature should be used.

This bug was introduced in 4.3 as a "fix".

### Steps to reproduce behavior

1. Pick a product
2. Unset "Visible on storefront"
3. Resync
4. Now product is in Draft.

### Screenshot/Video
<img width="340" alt="Screen Shot 2020-11-23 at 10 04 40 AM" src="https://user-images.githubusercontent.com/341412/99988220-5c71f200-2d7f-11eb-8ac1-3dc6cccce9b6.png">

### Workaround or possible solution

Remove the code that added this feature.

**Comment by yuenvision** [comment]
@topher1kenobe I may be misunderstanding what you're saying here, but Storefronts ARE Channels. It's a type of Channel, but managing product visibility on a Storefront means we have to manage the visibility on the Channel. Hiding it in the Storefront results in it hiding on the Channel in WP. Your steps to reproduce are describing exactly the expected behavior.

**Comment by topher1kenobe** [comment]
The "Visible on storefront" in this context has no bearing on Channels at all. Changing this setting in either direction does not affect the WordPress site. "storefront visibility" in the context of WordPress is on a per-channel basis in another UI.

**Comment by yuenvision** [comment]
We are respecting the storefront visibility setting, which was a pre-channels setting, used to show/hide products on a BC storefront. It is a global setting to show/hide the product, which should be respected, even at the channel level. It is, and always has been, a global setting at the Catalog level. 

There is also a Channel listing state for active and disabled, which WP also respects (and sets, if the user changes the product to Draft or Published in WP). 

There is no visible BC UI to change the Channel Listing state today. That needs to be added so that merchants can show/hide products at the Storefront level. 

But the scope of the storefront visibility setting and the scope of the WP response to that setting is still correct. The label of "storefront visibility" is confusing since "storefront" means something different today than it did when this setting was originally conceived.
