### ISSUE TITLE
In IE 11, Javascript error on "Remove from cart"

### ISSUE THREAD

**Issue by NewVibe** [bigcommerce/bigcommerce-for-wordpress#248]
### Expected behavior
Clicking "Remove from cart" in the mini-cart or the cart page will result in the item disappearing from the page (as well as being removed from the cart.

### Actual behavior
The item remains on the page, even though a refresh reveals it has actually been removed from the cart.

### Steps to reproduce behavior

1. In IE 11 add an item to the cart
2. In IE 11, visit the cart page and click "Remove item from cart"

Note:  an error is visible in the console:  Object doesn't support property or method 'forEach'

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by amckemie** [comment]
@NewVibe Did you reach out to partner support at BigCommerce for this issue? That's generally the recommended path when bugs arise with any product, so that they can help identify whether there are configuration or other issues at play causing the bug. 

Can you share the following information:

- What version of the plugin you are using? 
- Was this working before? If so, when did it stop?
- What theme are you using?

And can you repost the screenshot of the image and share a screen recording please? All of this info will help us to better pinpoint and resolve the issue. Thanks!

**Comment by keyinora** [comment]
Most likely they will tell you that they don't plan on adding fixes for that browser. I'd look into solutions to push users to update their browser to something else.

Example, using: http://browser-update.org/ free script.

`
<script type="text/javascript">
	var $buoop = {
		required:{e:0,f:0,o:0,s:0,c:0,i:999},
		test:false,
		text: {
			'msg':'Your web browser ({brow_name}) is out of date.',
			'msgmore': 'Use another browser for more security, speed and the best experience on this site.', 
			'bupdate': 'Use Another Browser',
			'bignore': 'Ignore',
			'remind': 'You will be reminded in {days} days.',
			'bnever': 'Never show again'  
		},
		newwindow: true,
		style:"corner",
		insecure: true,
		unsupported: true,
		mobile: true,
		shift_page_down: true,
		api: 2020.08,
		reminder: 0,
		reminderClosed: 1
	};

	function $buo_f(){
		var e = document.createElement("script");
		e.src = "//browser-update.org/update.min.js";
		document.body.appendChild(e);
	};
	try {document.addEventListener("DOMContentLoaded", $buo_f, false)}
	catch(e){window.attachEvent("onload", $buo_f)}
</script>
`

**Comment by tyla-taylor** [comment]
Unfortunately, we are not supporting IE11 at this time.
