### ISSUE TITLE
Is It Possible To Just Use The BigCommerce CDN for the Product Photos?

### ISSUE THREAD

**Issue by harnerdesigns** [bigcommerce/bigcommerce-for-wordpress#268]
There's no need to store the images in 2 places (WP and BC CDN). 

### Expected behavior

1. Sync Product Data between BigCommerce and WordPress.
2. Store the cdn.bigcommerce.com url as post-meta in WP
3. Don't take up 10GB of storage space on my server.

### Actual behavior

1. Sync Product Data between BigCommerce and WordPress
2. Imports the image into WordPress and stores it as the Featured Image
3. Takes up 10GB of storage space on my server.

### Workaround or possible solution

Store the BC CDN URL as a Post Meta field for each product. Remove the "Featured Image" support from the Product Post type, and then use that URL as the `<img src=" < CDN Link >" />` on the product pages.

Would require a total rework of how images are handled, but would save so MUCH space and Syncing products would probably be much faster since it's not transferring a ton of images.

**Comment by yuenvision** [comment]
We understand that it's cumbersome to store images in two places and also take up WP hosting storage. While the answer _is_ a CDN, right now, the best solution is not BC's CDN because WordPress requires resized assets to accommodate  registered images within the theme. BC's CDN does not allow for resizing on the fly like other CDNs (ex: Cloudinary, Google, etc). Until it does, it will not be a valid option for headless asset delivery. 

In the meantime, I recommend installing a CDN WP plugin that will upload any of your assets to the CDN repo, remove them from your WP host's storage, and reference the CDN link in the WP DB.
