### ISSUE TITLE
Is there a feature for instock notification for wordpress?

### ISSUE THREAD

**Issue by theanswer026** [bigcommerce/bigcommerce-for-wordpress#287]
### Expected behavior
Add form on product page

### Steps to reproduce behavior

1.
2.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by bc-hnbarr** [comment]
You could look at using this app -- https://www.bigcommerce.com/apps/stocknotify 
The description mentions that you can use with headless storefronts via api. :)

**Comment by theanswer026** [comment]
@bc-hnbarr Hi. Thanks for the response. I'm not good at apis though. Is there a simpler way? Say using a shortcode instead? Thanks again

**Comment by yuenvision** [comment]
By default, if you have tracking stock enabled in the BC admin, you can set a low stock threshold in the BC settings and the plugin will respond in the following ways: 

- If the product has greater than the low stock threshold, there is no notification on the product detail page nor the product category lander
- If the product has fewer than or equal the low stock threshold value, it displays a low stock notification, indicating how many are left in stock
- If the product is out of stock, it displays an "out of stock" notification and the product is not able to be added to the cart

As such, there is no In Stock notification because the ability to purchase the product indicates that it is in stock. 
We also respect pre-order settings and availability windows set in the BC admin.

In the plugin settings, you can activate or deactivate inventory webhooks to ensure that your store is always in sync with your stock levels (this can occasionally lead to DDOS flags on your WP host, depending on your host's sensitivity to pings from external servers, however).
