### ISSUE TITLE
Query Parameters not Added to Dynamic Checkout for redirection to bigcommerce hosted checkout. Major issue.

### ISSUE THREAD

**Issue by snoroozi** [bigcommerce/bigcommerce-for-wordpress#292]
Here is my is issue in full in regards to dynamic checkout link with bigcommerce for WordPress plugin.

To understand please try the following:

1. Go to thegreennursery.co and add a product to cart and then proceed to checkout. You will be taken to thegreennursery.com where our main bigcommerce checkout is. You will notice the query parameters needed to pass the cookie are not present on the checkout url because of the dynamically generated checkout link(button) on the bigcommerce for WordPress plugin.

2. Clear cart and cookies and then try this. Go to thegreennursery.co and add a product to cart. Then visit this url where I have made just static checkout urls for testing purposes. https://thegreennursery.co/test-checkout-links/

Click on the first link titled "full checkout url". You will see in this case the query parameters for both analytics and matomo analytics are added to the checkout link.

Matomo tells exactly how to handle this issue in their documentation for JavaScript dynamic links, but I don't know how to convert that to php. You can find the info under this header "Advanced: Handling Dynamically Generated Links"
Here https://matomo.org/faq/how-to/faq_23654/

To be clear, I'm already passing revenue etc. The tracking scripts are working. The only thing not working is passing the cookie for cross domain tracking. The only time it is passed is when a customer chooses to edit cart or some other reason return to thegreennursery.co before checkout. In these rare cases the cookie is added when navigating backwards momentarily.

I mean all the tracking scripts are in place. But the cookie handling because of the dynamic link make it not work.

I'm currently trying to find a php developer to patch until addressed.

**Comment by tyla-taylor** [comment]
Cross-domain is supported by the platforms but needs to be configured in the Segment/GA settings and that the redirection URL should be set in BC’s routes config, rather than passed through as a URL param. If you need more support, we suggest reaching out to BCs support team and have them help with Matomo config and BC platform accommodations.

**Comment by snoroozi** [comment]
@tyla-taylor their support did not help with this issue which is why I posted here. Can you be more specific who and what exactly to ask of them?

**Comment by yuenvision** [comment]
Hi, @snoroozi!
I'm not sure who to ask for at BC. You'd want to speak with someone who has specific BC4WP knowledge, so that's the first thing to request. Generally, the BC Support team is broadly more familiar with the BC Stencil platform, and you'll need someone with more specialized expertise. 

Here are a few resources to get you pointed in the right direction:

BC Analytics - https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress?language=en_US#analytics
BC Checkout - https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress-Checkout?language=en_US
GA Cross-Domain Management - https://support.google.com/analytics/answer/1033876?hl=en#zippy=%2Cin-this-article
GA Cross-Domain Setup - https://support.google.com/analytics/answer/1034342?hl=en#zippy=%2Cin-this-article

The high level is that you need a domain for your store, a sub-domain for your checkout, and then they both need to be registered to your GA account and connected in the Conversion Funnels.

**Comment by snoroozi** [comment]
@yuenvision that's the problem is that my setup is not domain frontend with sub domain checkout.  I can't make it that way either because I also use my bc hosted site.

The parameters do not get passed when using a different domain for checkout.

**Comment by snoroozi** [comment]
Already been through Google support, bc support, paid devs etc

**Comment by yuenvision** [comment]
Ok, so what you have is a multi-storefront and it's not possible for you to host the WP instance and the Checkout on the same domain but with different sub-domains. 

Unfortunately, for the time-being, BC shares the same checkout across all storefronts. The solution you have in place for a redirected checkout is the best one until they are able to fully support Multi-Storefront with multiple checkouts. Embedded checkout will ONLY work within the same domain.

**Comment by snoroozi** [comment]
@yuenvision yes I already learned all that the hard way.  The problem is in my setup you are not sending the ga parameters on the dynamic checkout button.  That would solve the issue.
