### ISSUE TITLE
Import stops if page closed

### ISSUE THREAD

**Issue by ProcureSam** [bigcommerce/bigcommerce-for-wordpress#322]
### Expected behavior
I run a large store on BC, we're looking into doing a second storefront via WP. We're in the initial syncing phase of everything. I would expect the sync process to happen regardless of whether the page is open. This hasn't been the case. I close t he site. Sync'ing stops.

### Actual behavior
Syncing only works while the admin board is opened.

### Steps to reproduce behavior

1. Have a lot of skus
2. Try to import them

### Workaround or possible solution

At the moment, my only solution is to leave the WP dashboard open and hope that's enough. This seems like it would be a problem for real-time sync/catching updates in BC.

--

The wordpress install is brand new. It's a pre-made/ready to deploy image on DigitalOcean. It has been firewalled off from the internet (only talks to my workstation and BC), so I'm fairly certain no hackers or the like have caused issues. 

I am reading through the plugin code, it SEEMS like things should just keep running. Cron_Runner.php has comments that "This will have the side effect of scheduling the next run, so the cron can continue if the user leaves the page and ajax requests stop." However, it looks like it only schedules 1 further batch (up to 25 products/limit?) and then stops there.

**Comment by tyla-taylor** [comment]
Hi @ProcureSam, are you still experiencing this same behavior with syncs since setting up your new WP install?

**Comment by yuenvision** [comment]
@ProcureSam, the sync process utilizes `wp_cron()` to process the importer and that function does require that a window stay open to keep the connection live. That's just how WP works. You can, however, set up a server-side cron to keep the connection alive in the background so you do not need to keep a window open in order to complete a sync. 

[Here are some details on how to set that up. ](https://docs.google.com/document/d/13aMtT_oHIlHfMFpZzjaXfkHOCGHgwmzo55ts8MUt6vI/edit#heading=h.4rzbz93ezu3r)
