### ISSUE TITLE
Problem with products with variants

### ISSUE THREAD

**Issue by Donnnaemm** [bigcommerce/bigcommerce-for-wordpress#334]
The expected behavior is for the "Add to Cart" button to be active when a customer chooses the size of the shirt.

The actual behavior is that the "Add to Cart" button is greyed out on the WordPress Elementor side. However, the product works fine on the Bigcommerce side.

### Screenshot/Video (if applicable)
![image](https://user-images.githubusercontent.com/57815707/156216793-9ef39e99-5a37-4acf-b1a7-a084f2a01f73.png)
![image](https://user-images.githubusercontent.com/57815707/156217211-a6242d3d-dc7d-4c04-904f-31bf75efe3ec.png)
![image](https://user-images.githubusercontent.com/57815707/156217400-d0951723-e683-41a4-ac85-405214291d37.png)

Has anyone experienced this or know how to fix this, please? Thank you very much in advance for any assistance you can give me.

**Comment by yuenvision** [comment]
This can happen if WP interprets from the BC API that the variant is out of stock. Are you tracking stock in the BC product admin?

**Comment by Donnnaemm** [comment]
Hi Thank you so much for replying back! Yes, I am tracking stock on those variants and all of them have current inventory as quantity of 5 each of the six different sizes (variants.)

**Comment by yuenvision** [comment]
Ok. It's possible that you have a cache that needs to be busted in order to correct this. Have you performed a product sync (either full or partial) since this issue appeared? If you have a memcache, any other object cache, that would also need to be cleared.

**Comment by yuenvision** [comment]
Hey, @Donnnaemm,
I had one of my devs take a look at your issue as well. 

1. He confirmed that it could be a product cache, as I'd mentioned before. If that's the case, then running a product sync from the plugin should bust that cache. The caveat would be if you also have an object cache running. A front-end cache could also create this issue. e.g check your various cache policies since the symptom is that you aren't seeing the correct data in the JS scripts.

2. Another possibility is that it's a JS conflict in your theme or a plugin. My dev tested on the free Elementor theme(OceanWP) and could not reproduce the issue. However, if you have some theme customizations or plugins installed on your instance, you may be experiencing script execution issues due to markup errors. Check your browser console to see if there are any JS scripts that are erroring out or not running when you attempt to load a page.
