### ISSUE TITLE
Product Sync

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#39]
When the product sync gets stuck and does not make any progress for a considerable amount of time, what is the recommended action to take?

For example, on one client, the message "Import in progress. Status: Importing products. 292 remaining." has been the same for quite a while now.

Is there a log somewhere that we've missed that may help us pin point the problem?

**Comment by 5874** [comment]
@karen-white @topher1kenobe Re the bug mentioned on 25 September, was this fixed? I'm wondering if it's related to all the issues we're currently having with v 1.0 #101 #99 

Another shout for logs as well please!! ( #100 )

**Comment by karen-white** [comment]
@5874 Does the store with the current stuck import have empty custom field values on products? I can check with MT to see if we've changed the way the plugin handles that error, but on the BigCommerce side, blank values for custom fields are not allowed. This behavior changed about a year ago: It used to be the case that you could save a product with blank custom field values, but we updated our code to reflect the correct behavior, which is to require a value. That being said, the plugin should handle the exception better and direct the user to add custom field values instead of stopping the import.

**Comment by 5874** [comment]
@karen-white Not as far as I know, no. And if it's a required field, I'm not sure how it could have?

**Comment by karen-white** [comment]
@5874 It's a required field that used to not be required--so stores that were set up prior to the update could have blank custom field values. If the user tried to save that product now, they would see an error because the blank value no longer validates. But if your products don't have blank custom field values, we'd need to explore other causes for the stuck import.

**Comment by 5874** [comment]
@karen-white the site in question is Carluccios. Which is not a year old.

**Comment by 5874** [comment]
@karen-white It would be super if our most recent issues were addressed please.

**Comment by karen-white** [comment]
Trying to help @5874 . We're discussing the current issues you're seeing with the team right now.

**Comment by karen-white** [comment]
@5874 The latest plugin version (1.1.0) includes a Diagnostic log to help troubleshoot stuck imports. I'm going to close this issue for now, but please feel free to reopen if you're able to get the log detail and we can go from there!
